Algoritmo "teste6"
//
//
// Descrição   :    informar ano
// Autor(a)    : Joao victor da silva martins
// Data atual  : 31/03/2020



Var

   idadeuser:inteiro
   nomeuser:caractere
   dataatual:inteiro
   resultado:inteiro
Inicio
  dataatual <- 2020
  Escreval ("Digita seu nome")
  Leia(nomeuser)
  Escreval ("Digita sua idade")
  Leia(idadeuser)
  resultado <- idadeuser - dataatual
  escreval ("você nasceu em ",resultado)
  


Fimalgoritmo