Algoritmo "teste5"

     //
//
// Descrição   : Soma número usuário
// Autor(a)    : Joao Victor da silva martins
// Data atual  : 31/03/2020

Var

  Valoruser1:inteiro
  valoruser2:inteiro
  resultado:inteiro
Inicio
    Escreval("escreva um número")
    Leia(valoruser1)
    Escreval ("Escreva segundo número")
    Leia (valoruser2)
    resultado <- valoruser1 + valoruser2
    
    Escreval("O resultado é", resultado)


Fimalgoritmo