Algoritmo "teste8"
// Disciplina  :  [Linguagem e Lógica de Programação] 
// Professor   : ?
// Descrição   : Interrompa só quando pressionar f
// Autor(a)    : Joao Victor da silva martins
// Data atual  : 31/03/2020
Var
continuar: caracter



inicio


continuar:="a"
enquanto continuar <> "f" faca
escreval ("A mensagem será interrompida quando a tecla F for pressionada.")
leia (continuar)
fimenquanto
escreval ("A letra F foi pressionada")

fimalgoritmo


Fimalgoritmo