Algoritmo "teste6"
// Disciplina  :  [Linguagem e Lógica de Programação] 
// Professor   : ?
// Descrição   : Informar nome e nota de 30 alunos
// Autor(a)    : Joao victor da silva martins
// Data atual  : 31/03/2020
Var
// Seção de Declarações das variáveis 
   Nome:caractere
   nota:caractere
   i:inteiro

inicio

para i de 1 ate 30 faca
escreval("Informe o nome do ", i, "º Aluno: ")
leia(nome)
escreval("Informe a Nota do ", i, "º Aluno: ")
leia(nota)
fimpara


Fimalgoritmo